### ISSUE TITLE
I am not added as a contributor to this project

### ISSUE THREAD

**Issue by caupcakes** [Devakm701/Billiards#6]
# This is important.

**Comment by Hopeyro** [comment]
![adi pillow](https://user-images.githubusercontent.com/71350255/168412799-685c0535-97bc-4c3e-abb8-72442929f8b2.jpg)

**Comment by Devakm701** [comment]
Banned

**Comment by caupcakes** [comment]
@Hopeyro would you like to address one of your branch names?
